version: "3.8"

services:
    db:
        image: postgres:latest
        container_name: go_analytics_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: go-analytics
        ports:
            - "5432:5333"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./internal/database:/docker-entrypoint-initdb.d

volumes:
    db_data:
